### ISSUE TITLE
[Feature] Merge this project into sjb-cheatsheet in a way that allows the pieces to stay modular

### ISSUE THREAD

**Issue by sicklybeans** [sicklybeans/sjb-tools#12]
This might be impossible. 

Recall: One of the key goals of this project is a lightweight library that handles Todo lists in easy to understand reusable ways with minimal external dependencies. The project should be decoupled from other efforts.

However, there is a lot of code overlap between this project and sjb_cheatsheet (in fact the Issues are basically identical).

I should consider trying to merge them into a single github project in a way that allows for them to be installed separately.

depends on #4

**Comment by sbryant1014** [comment]
You should use githubs 'projects' feature and 'labels' for issues to keep the issues separate as needed
